# Generated by Django 4.2.27 on 2026-01-06 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code (e.g., CS, EC, ME)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Division name (A, B, C, etc.)', max_length=10, unique=True)),
                ('max_students', models.IntegerField(default=60, help_text='Maximum students in this division', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LecturePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Period name (e.g., Lecture 1, Lab Session 1)', max_length=50)),
                ('period_number', models.IntegerField(help_text='Period number in daily sequence', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether this period is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['period_number'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('min_attendance', models.IntegerField(default=75)),
                ('grace_period', models.IntegerField(default=10)),
                ('auto_absent', models.BooleanField(default=False)),
                ('notify_parents', models.BooleanField(default=False)),
                ('faculty_reminder', models.BooleanField(default=False)),
                ('hod_summary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Subject code (e.g., CS301)', max_length=20, unique=True)),
                ('credits', models.IntegerField(default=3, help_text='Credit hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('semester', models.IntegerField(help_text='Semester number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='dashboard.department')),
            ],
            options={
                'ordering': ['semester', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('roll_number', models.CharField(blank=True, help_text='Roll number within division', max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Optional contact number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('class_year', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=2)),
                ('is_trained', models.BooleanField(default=False, help_text='Has face encoding been captured')),
                ('is_active', models.BooleanField(default=True, help_text='Is student currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Academic department', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='dashboard.department')),
                ('division', models.ForeignKey(blank=True, help_text='Class division', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='dashboard.division')),
            ],
            options={
                'ordering': ['class_year', 'roll_number'],
            },
        ),
        migrations.CreateModel(
            name='LectureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=2)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('room_number', models.CharField(blank=True, help_text='Classroom/Lab number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dashboard.division')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='dashboard.faculty')),
                ('lecture_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dashboard.lectureperiod')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dashboard.subject')),
            ],
            options={
                'ordering': ['class_year', 'division', 'weekday', 'lecture_period'],
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_data', models.TextField(help_text='JSON serialized face encoding array')),
                ('image_path', models.CharField(help_text='Path to stored face image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to='dashboard.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=2)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('total_students', models.IntegerField(default=0, help_text='Total students in this class/division')),
                ('present_count', models.IntegerField(default=0, help_text='Students marked present')),
                ('absent_count', models.IntegerField(default=0, help_text='Students marked absent')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='dashboard.division')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='dashboard.faculty')),
                ('lecture_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='dashboard.lectureperiod')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='dashboard.subject')),
            ],
            options={
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of attendance')),
                ('marked_at', models.DateTimeField(auto_now_add=True, help_text='Exact time when attendance was marked')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('marked_by_face', models.BooleanField(default=False, help_text='Was attendance marked using face recognition')),
                ('confidence_score', models.FloatField(blank=True, help_text='Face recognition confidence (0-1)', null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture_period', models.ForeignKey(blank=True, help_text='Lecture period when attendance was marked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.lectureperiod')),
                ('session', models.ForeignKey(blank=True, help_text='The attendance session this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.student')),
                ('subject', models.ForeignKey(blank=True, help_text='Subject for which attendance was marked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dashboard.subject')),
            ],
            options={
                'ordering': ['-date', '-marked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_year', 'division'], name='dashboard_s_class_y_561fea_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_trained', 'is_active'], name='dashboard_s_is_trai_0443e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lectureschedule',
            unique_together={('class_year', 'division', 'lecture_period', 'weekday')},
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['date', 'class_year', 'division'], name='dashboard_a_date_f3723f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status'], name='dashboard_a_status_0f1454_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['-date', '-marked_at'], name='dashboard_a_date_904468_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='dashboard_a_student_dc555d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status'], name='dashboard_a_session_cc23fe_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['subject', 'date'], name='dashboard_a_subject_9fe22f_idx'),
        ),
    ]
