# Generated by Django 4.2.27 on 2026-01-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student photo for face recognition (alternative to camera capture)', null=True, upload_to='student_photos/'),
        ),
    ]
