# Generated by Django 4.2.27 on 2026-01-09 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='secondary_phone',
            field=models.CharField(blank=True, help_text='Optional secondary contact number', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='0000000000', help_text='Primary contact number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='TEMP', help_text='Roll number within division', max_length=10),
        ),
    ]
